//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using xCheatsFunctions;

namespace System.Configuration
{
    internal class ApplicationSettingsBase
    {
        protected static Global Synchronized(Global global)
        {
            throw new NotImplementedException();
        }
    }
}